name: Deploy to Lambda

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Create package folder
      run: |
        mkdir ${{ github.workspace }}/dist
    - name: Add source files to package
      run: |
        mv ${{ github.workspace }}/src ${{ github.workspace }}/dist
        # lambda_function.py needs to be top level
        mv ${{ github.workspace }}/dist/src/lambda_function.py ${{ github.workspace }}/dist/lambda_function.py
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv run pipenv install
        pipenv run pip freeze > ${{ github.workspace }}/requirements.txt
        pipenv run pip install -r ${{ github.workspace }}/requirements.txt -t ${{ github.workspace }}/dist
    - name: Update permissions
      run: |
        chmod -R 755 ${{ github.workspace }}/dist/*
    - name: .zip package
      run: |
        cd ${{ github.workspace }}/dist
        zip -r ${{ github.workspace }}/package.zip *
    - name: Upload package artifact
      uses: actions/upload-artifact@1.0.0
      with:
        name: lambda-package
        path: ${{ github.workspace }}/package.zip
    - name: Update Lambda
      uses: stcalica/update-lambda@0.0.2
      with:
        package: package.zip
        function-name: answerCallbox
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
